language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements/test.txt
  - pip install .
script:
  - pytest --rootdir=tests --log-level=INFO --cov=source/moprofiler --cov-branch --cov-report=xml:reports/coverage.xml -s tests
dist: trusty
addons:
  sonarcloud:
    organization: "littlemo-github" # the key of the org you chose at step #3
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
