language: python
dist: trusty
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements/test.txt
  - pip install .
addons:
  sonarcloud:
    organization: "littlemo-github"
before_script:
  - git fetch --unshallow
script:
  - coverage erase
  - coverage run --branch --source=source/moprofiler pytest
  - coverage xml -i -o reports/coverage.xml
  - sonar-scanner
